### ISSUE TITLE
Add support for custom tokens

### ISSUE THREAD

**Issue by elias-garcia** [0xPolygonHermez/zkevm-bridge-ui#118]
This issue describes the new workflow proposed to manage the custom tokens ([v1.0.3 in Figma](https://www.figma.com/file/KsuEveavWfON3Y2sgf96Jf/Polygon-Hermez-Bridge?node-id=2598%3A720)) through the token selection modal.

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182537456-a9a6930a-4113-4760-9db3-59d945b9a6a8.png" />

The info button in the token opens the token info screen, which shows all the token details.

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182542482-a3688ae8-588c-4a12-ae6e-734c3116406d.png" />

* The address of the contract on both L1 and L2
  * A button to copy the address
  * A button to open the contract in the explorer
* The name of the token
* The symbol of the token
* The decimals of the token

If the token is a custom token added by the user, a button "Remove custom token" is shown.

The back button returns the user to the list of tokens.

To add a custom token, the user needs to provide the address of the contract in the search input. When the user types the address of a token two things can happen:

1. If the token is present in the list of default tokens, the list is filtered using partial matching against the token's address, name, and symbol.
2. If a complete, valid token address is provided and the contract is deployed in the blockchain, but the token is not present in the list of default tokens, a new token is shown, which can be added as a custom token by clicking the _Add token_ button.

While the custom token is loading we will show a gray spinner.

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182537721-5893eccb-2b2e-4d7d-9bb8-c82617148f16.png" />

After clicking the _Add token_ button the user is presented with the _Add token_ modal screen:

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182538007-374a85df-912f-4ebf-b89e-98f06f0876a7.png" />

Once an L1 token is added, the app will automatically list the token when the L2 network is selected.

## Errors

When the user inputs text in the _Token List_ search input, two scenarios are possible:

1. The text is not a valid address: In such a case, we filter the list of tokens and if nothing is found we show the following message:

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182544312-1d4f71ce-3cda-4aaa-a952-7e2e57399cbc.png" />

2. The text is a valid address: In such a case, we try to instantiate the contract, and if it can not be found we show the following message:

<img width="400px" src="https://user-images.githubusercontent.com/15896177/182544457-87599fce-08f8-42e3-af9d-04f008dd3de1.png" />

**Comment by amonsosanz** [comment]
Finally, it has been decided to remove the "Manage Custom Tokens" screen (which only has the remove button) and put the remove button in the context menu of the token.

This has several advantages:

1. The obvious one of not having to add an extra screen.
2. Avoid the 3-level hierarchy that the initial proposal had `Token List > Manage Custom Tokens > Add token`
3. Avoid the ambiguity of what the back button should do based on how you got to the "Add Token" screen. (`Token List > Manage Custom Tokens > paste address > Add token` vs `Token List > paste address > Add token`)
4. Avoid having to consider the "Token already supported" case if you add a supported address on the "Manage Custom Tokens" screen.

In this way, when you paste the address of a token:
* If the token is supported by default, you have the menu with the options "View token info" and "Go to token contract"
* If the token is not supported by default but you have already added it in the past, you have the menu with the options "View token info", "Go to token contract" and "Remove custom token"
* If the token is not supported by default and you don't have it added, the "Add token" button appears and if you click it, you go to the token details screen but with the disclaimer "Interact carefully..." and the "Add <" button token>"
