### ISSUE TITLE
Improve error display

### ISSUE THREAD

**Issue by amonsosanz** [0xPolygonHermez/zkevm-bridge-ui#157]
We need to improve how we present both the red errors and the error snackbar once the design team provides a design.

**Comment by elias-garcia** [comment]
Chami updated today the error snackbar styles: https://www.figma.com/file/KsuEveavWfON3Y2sgf96Jf/Polygon-Hermez-Bridge?node-id=2598%3A2704

 I've added the new styles in #166 but we still need to improve:

- Decide and implement the hover styles for the "X" and the "Report" buttons.
