### ISSUE TITLE
Incorrect gas params when doing a L2 claim

### ISSUE THREAD

**Issue by elias-garcia** [0xPolygonHermez/zkevm-bridge-ui#182]
Jordi found a bug when trying to perform a claim in L2. Probably we are not setting the gas params properly:

![IMAGE 2022-10-06 10:21:17](https://user-images.githubusercontent.com/6737805/194263165-6da21928-8262-423c-9eeb-9fe32d7b72a9.jpg)

![IMAGE 2022-10-06 10:21:20](https://user-images.githubusercontent.com/6737805/194263172-137a7bb4-c4bd-4164-858e-bf0d1137e61b.jpg)

**Comment by elias-garcia** [comment]
This should be fixed in #210.

**Comment by amonsosanz** [comment]
Can't we close this @elias-garcia?

**Comment by elias-garcia** [comment]
We can close it as it didn't happen again.
