### ISSUE TITLE
Add support for the new `forceUpdateGlobalExitRoot` param of the `bridgeAsset` method

### ISSUE THREAD

**Issue by amonsosanz** [0xPolygonHermez/zkevm-bridge-ui#257]
The method `bridgeAsset` will include a new boolean param `forceUpdateGlobalExitRoot`. At this iteration the value for the param will depend solely on the origin network of the bridge:

* Bridges initiated on L1: `false` 
* Bridges initiated on L2: `true`

In a future iteration, the node team may implement a feature that allows us to optimize this further but for now, we will always send `true` for L2 bridges.

Notice also that the `token` param has its position changed.

**Comment by jesusholoo** [comment]
Here are the PR with the new updated ABI https://github.com/0xPolygonHermez/zkevm-contracts/tree/feature/optimizations
