### ISSUE TITLE
PROOF_OF_EFFICIENCY_CONTRACT for sepolia

### ISSUE THREAD

**Issue by josojo** [0xPolygonHermez/zkevm-bridge-ui#279]
Hello,

I would like to have a PROOF_OF_EFFICIENCY_CONTRACT for sepolia.

where can we find the contract source code to deploy it? From the goerli source, it seems like this was an old contract in zkevm-contracts repo. But the contract is no longer in the repo.

Where can we find it to deploy it? Or should this be removed, as the new zkevm-contracts no longer uses this contract?

Thanks for your help

**Comment by josojo** [comment]
Okay, got it. The contract should be just the zkevm from here:
https://github.com/0xPolygonHermez/zkevm-contracts/blob/53e95f3a236d8bea87c27cb8714a5d21496a3b20/docs/PolygonZkEVM.md?plain=1#L500

So a renaming is all that is needed, no real code changes. 
Feel free to close it, since its just a naming issue. 
If I should write the PR, let me know. happy to do it.

**Comment by elias-garcia** [comment]
Hi @josojo! Yeah, you are right, that's the Proof of Efficiency contract that you should deploy on Sepolia. Thanks for pointing it out :)
