### ISSUE TITLE
Security Risk: DoS on the exposed L1 RPC

### ISSUE THREAD

**Issue by bap2pecs** [0xPolygonHermez/zkevm-bridge-ui#290]
## Problem

from the bridge UI, open developer console, you can actually find the RPC url for the l1.

so that means anyone can use your RPC for free, which can lead to potential DoS situations

this is also the case for the official Polygon bridge on https://portal.polygon.technology/bridge

## Proposed Solution

ideally it should just use the rpc provider via user's web3 wallet (e..g Metamask)

**Comment by elias-garcia** [comment]
Hi! You can see both RPC URLS's, for L1 and L2. If you want to be able to display balances on both networks at the same time you can't use just the RPC Provider of the user wallet, so the proposed solution won't work for how the UI was designed to work (and to improve user experience).

Anyway, this happens with any other public API service out there... You can always build a proxy backend to rate-limit the calls, use CORS etc (which Infura, Alchemy and other RPC providers already support BTW).

**Comment by bap2pecs** [comment]
using CORS is a good idea to fix. but just FYI, @elias-garcia, Polygon is now exposing its quicknode API key to the public without protection.

![image](https://github.com/0xPolygonHermez/zkevm-bridge-ui/assets/111917526/955905bd-9386-4f62-ad66-73ea126f3447)
